spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: 31536000000

openai:
  api-key: ${OPENAI_API_KEY}
kakao:
  client-id: ${KAKAO_CLIENT_ID}
